name: MacOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install gperf
      - name: Build
        run: |
          mkdir build; cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DTH_ENABLE_ASAN=ON -DTH_ENABLE_UBSAN=ON
          make -j$(nproc)
      - name: Test
        run: |
          cd build
          ctest --output-on-failure
